import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";
import ModeSelector from "./components/ModeSelector";
import Tojjle from "./components/Tojjle";
import { CameraProvider } from "./contexts/CameraContext";
import StartCameraTojjle from "./camera/StartCameraTojjle";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weights: ["400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-back text-mainText antialiased ${inter.className}`}
      >
        <Toaster />
        <Navbar />
        {/* <ModeSelector /> */}
        <CameraProvider>
          <StartCameraTojjle isLinkToCamera={true} />
          {children}
        </CameraProvider>
      </body>
    </html>
  );
}
